# Positions of jukeboxes in the world (`World, X, Z, Y`)
jukeboxes:
  - "World, -195, 50, 82"

# Music volume (float)
baseVolume: 1.0

# Purchase link
displayPurchaseLink: pvpclub.craftingstore.net
fullPurchaseLink: https://pvpclub.craftingstore.net

