name: CornrootMusic
version: '${version}'
main: com.connorcode.cornroot.Cornroot
api-version: 1.16
authors: [ ConnorSlade ]
description: A music system
website: https://connorcode.com
commands:
  music:
    description: Opens the jukebox GUI
    usage: music
  globalkeyadd:
    description: Give player access to playing global music
    usage: globalkeyadd <UUID> [Count]
  globalkeyremove:
    description: Remove keys from a player
    usage: globalkeyremove <UUID> [Count]
  globalkeylist:
    description: List player with global music perms
    usage: globalkeylist